CREATE DATABASE IF NOT EXISTS PoultryFarmManagementSystem;

USE PoultryFarmManagementSystem;

CREATE TABLE IF NOT EXISTS Users (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    FirstName VARCHAR(100) NOT NULL,
    LastName VARCHAR(100) NOT NULL,
    Category VARCHAR(50) NOT NULL,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Houses (
    hse_ID INT AUTO_INCREMENT PRIMARY KEY,
    hseName VARCHAR(100) NOT NULL UNIQUE,
    Capacity INT DEFAULT 0,
    Status TINYINT(1) DEFAULT 0,
    DateAdded DATE DEFAULT (CURRENT_DATE),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Feed (
    feed_ID INT AUTO_INCREMENT PRIMARY KEY,
    feed_Type VARCHAR(100) NOT NULL UNIQUE,
    Description TEXT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS FeedConsumption (
    entry_ID INT AUTO_INCREMENT PRIMARY KEY,
    date DATE NOT NULL,
    feed_ID INT NOT NULL,
    hse_ID INT NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    remark VARCHAR(255),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_feed FOREIGN KEY (feed_ID) REFERENCES Feed(feed_ID) ON DELETE CASCADE,
    CONSTRAINT fk_house_feed FOREIGN KEY (hse_ID) REFERENCES Houses(hse_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Brood (
    BroodID INT AUTO_INCREMENT PRIMARY KEY,
    Date DATE NOT NULL,               
    InitialSize INT NOT NULL,
    CurrentSize INT NOT NULL,
    HouseAssigned INT DEFAULT 0,
    Status TINYINT(1) DEFAULT 0,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_house_assigned FOREIGN KEY (HouseAssigned) REFERENCES Houses(hse_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Mortality (
    entry_ID INT AUTO_INCREMENT PRIMARY KEY,
    date DATE NOT NULL,
    number INT NOT NULL,
    hse_ID INT NOT NULL,
    remark VARCHAR(255),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_house_mortality FOREIGN KEY (hse_ID) REFERENCES Houses(hse_ID) ON DELETE CASCADE
);
